const http = require("http");
const https = require("https");
const fs = require("fs");
const path = require("path");

// Parse Neo4j nodeType format :`Label1`:`Label2` into ["Label1", "Label2"]
function parseNodeTypeLabels(nodeType) {
  return nodeType
    .split(":")
    .map((l) => l.replace(/`/g, "").trim())
    .filter(Boolean);
}

class TypeScriptViewGenerator {
  constructor(schema) {
    this.schema = schema;
  }

  generateAllViews() {
    // Collect all distinct labels with their properties
    const labelPropertiesMap = new Map();

    this.schema.nodes.forEach((node) => {
      console.log("processing node:", node.label);
      // Each node now has a labels array
      node.labels.forEach((label) => {
        // Merge properties for this label (dedupe by adding to existing)
        if (!labelPropertiesMap.has(label)) {
          labelPropertiesMap.set(label, new Map());
        }
        const propsMap = labelPropertiesMap.get(label);
        node.properties.forEach((prop) => {
          // Use property name as key to dedupe
          if (!propsMap.has(prop.name)) {
            propsMap.set(prop.name, prop);
          }
        });
      });
    });

    // Generate views for each distinct label
    labelPropertiesMap.forEach((propsMap, label) => {
      const properties = Array.from(propsMap.values());
      if (properties.length > 0) {
        console.log(`generating view for label: ${label}`);
        this.generateView(label, properties);
      }
    });

    // Generate the alias type to properties map
    this.generateAliasTypeMapFromLabels(labelPropertiesMap);
  }

  generateAliasTypeMapFromLabels(labelPropertiesMap) {
    const imports = [];
    const mapEntries = [];

    labelPropertiesMap.forEach((propsMap, label) => {
      if (propsMap.size > 0) {
        const constantName = this.getConstantName(label);
        const fileName = this.getFileName(label).replace(".ts", "");

        imports.push(`import { ${constantName} } from "./${fileName}";`);
        mapEntries.push(`  ${label}: ${constantName},`);
      }
    });

    const content = `// Auto-generated by generateReturnTypes.js - do not edit manually
${imports.join("\n")}

export const ALIAS_TYPE_TO_PROPERTIES_MAP: Record<string, { key: string; type: string }[]> = {
${mapEntries.join("\n")}
};
`;

    this.writeViewFile("AliasTypePropertiesMap.ts", content);
  }

  generateView(label, properties) {
    const fileName = this.getFileName(label);
    const constantName = this.getConstantName(label);

    // Generate base properties array
    const content = `export const ${constantName} = [${properties.map((prop) => `  { key: "${prop.name}", type: "${prop.type}" },`).join("\n")}];`;

    // Generate a valid TypeScript interface as a string template
    const labelInterface = `\nexport interface ${label}Properties {
${properties.map((prop) => `  ${prop.name}: ${this.mapSchemaTypeToTS(prop.type)};`).join("\n")}
}`;

    this.writeViewFile(fileName, content + labelInterface);
  }

  parseProperty(prop) {
    // Handle different property formats from schema
    if (typeof prop === "string") {
      return {
        name: prop,
        type: "string", // default type
      };
    } else if (prop.name && prop.type) {
      return {
        name: prop.name,
        type: this.mapSchemaTypeToTS(prop.type),
      };
    }

    return { name: prop, type: "string" };
  }

  mapSchemaTypeToTS(schemaType) {
    const typeMapping = {
      Double: "number",
      Long: "number",
      Integer: "number",
      String: "string",
      StringArray: "string",
      Boolean: "boolean",
    };

    return typeMapping[schemaType] || "string";
  }

  getViewName(label) {
    return label.replace(/[:`]/g, "");
  }

  getFileName(label) {
    const cleanLabel = this.getViewName(label);
    return `${cleanLabel}LabelView.ts`;
  }

  getConstantName(label) {
    const cleanLabel = this.getViewName(label);
    return `${cleanLabel.toUpperCase()}_LABEL_PROPERTIES`;
  }

  writeViewFile(fileName, content) {
    const viewsDir = path.join(__dirname, "../src/feature/Chunks/Views");
    const filePath = path.join(viewsDir, fileName);

    // Ensure directory exists
    if (!fs.existsSync(viewsDir)) {
      fs.mkdirSync(viewsDir, { recursive: true });
    }

    fs.writeFileSync(filePath, content, "utf8");
    console.log(` Generated view file: ${fileName}`);
  }
}

async function generateTypes() {
  try {
    // github sets CI=true during actions automatically
    const isCI = process.env.CI === "true";
    console.log("= Fetching schema from API for type generation...");
    console.log("> isCI:", isCI);

    // Determine API endpoint based on environment
    const baseUrl = isCI
      ? process.env.REACT_APP_SERVICE_URL
      : "http://localhost:8000";

    console.log(`< Environment: ${isCI ? "Production" : "Development"}`);
    console.log(`= API URL: ${baseUrl}`);

    // Fetch schema from API (reusing generateChunks.js logic)
    const response = await new Promise((resolve, reject) => {
      const url = new URL("/api/schema", baseUrl);
      const options = {
        hostname: url.hostname,
        port: url.port || (url.protocol === "https:" ? 443 : 80),
        path: url.pathname,
        method: "GET",
      };

      const requestModule = url.protocol === "https:" ? https : http;
      const req = requestModule.request(options, (res) => {
        let data = "";
        res.on("data", (chunk) => {
          data += chunk;
        });
        res.on("end", () => {
          try {
            resolve({ data: JSON.parse(data) });
          } catch (e) {
            reject(new Error("Invalid JSON response"));
          }
        });
      });

      req.on("error", reject);
      req.end();
    });

    // Parse labels into arrays
    const cleanedSchema = {
      ...response.data,
      nodes: response.data.nodes.map((node) => ({
        ...node,
        labels: parseNodeTypeLabels(node.label),
      })),
    };

    console.log(
      `=� Schema loaded: ${cleanedSchema.nodes.length} nodes, ${cleanedSchema.patterns.length} patterns`,
    );

    // Generate TypeScript views
    const generator = new TypeScriptViewGenerator(cleanedSchema);
    generator.generateAllViews();

    console.log(` TypeScript view files generated successfully`);
  } catch (error) {
    console.log(error)
    console.error("L Error generating types:", error.message);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  generateTypes();
}

module.exports = { generateTypes };
