// Auto-generated by generateReturnTypes.js - do not edit manually
import { CATEGORY_LABEL_PROPERTIES } from "./CategoryLabelView";
import { SUPPLIER_LABEL_PROPERTIES } from "./SupplierLabelView";
import { CUSTOMER_LABEL_PROPERTIES } from "./CustomerLabelView";
import { ORDER_LABEL_PROPERTIES } from "./OrderLabelView";
import { PRODUCT_LABEL_PROPERTIES } from "./ProductLabelView";

export const ALIAS_TYPE_TO_PROPERTIES_MAP: Record<string, { key: string; type: string }[]> = {
  Category: CATEGORY_LABEL_PROPERTIES,
  Supplier: SUPPLIER_LABEL_PROPERTIES,
  Customer: CUSTOMER_LABEL_PROPERTIES,
  Order: ORDER_LABEL_PROPERTIES,
  Product: PRODUCT_LABEL_PROPERTIES,
};
