export const PLAYER_GAME_INFO_PROPERTIES = [
  "player_game_id",
  "player_id",
  "player_display_name",
  "position",
  "recent_team",
  "season",
  "week",
  "opponent_team",
  "display_name",
  "player_name",
  "game_id",
  "won",
  "team",
];
