export const PLAYER_INFO_PROPERTIES = [
  "position",
  "display_name",
  "gsis_id",
  "last_name",
  "football_name",
  "short_name",
  "team_abbr",
  "college_name",
  "esb_id",
  "current_team_id",
  "first_name",
  "smart_id",
  "team_seq",
  "gsis_it_id",
];
