export const PLAYERSEASON_STATS = [
  { key: "season_type", type: "string" },
  { key: "completions", type: "number" },
  { key: "attempts", type: "number" },
  { key: "passing_yards", type: "number" },
  { key: "passing_tds", type: "number" },
  { key: "interceptions", type: "number" },
  { key: "sacks", type: "number" },
  { key: "sack_yards", type: "number" },
  { key: "sack_fumbles", type: "number" },
  { key: "sack_fumbles_lost", type: "number" },
  { key: "passing_air_yards", type: "number" },
  { key: "passing_yards_after_catch", type: "number" },
  { key: "passing_first_downs", type: "number" },
  { key: "passing_2pt_conversions", type: "boolean" },
  { key: "carries", type: "number" },
  { key: "rushing_yards", type: "number" },
  { key: "rushing_tds", type: "number" },
  { key: "rushing_fumbles", type: "number" },
  { key: "rushing_fumbles_lost", type: "number" },
  { key: "rushing_first_downs", type: "number" },
  { key: "rushing_epa", type: "number" },
  { key: "rushing_2pt_conversions", type: "number" },
  { key: "receptions", type: "number" },
  { key: "receiving_fumbles", type: "number" },
  { key: "fantasy_points_ppr", type: "number" },
  { key: "receiving_fumbles_lost", type: "number" },
  { key: "ay_sh", type: "number" },
  { key: "target_share", type: "number" },
  { key: "wopr_y", type: "number" },
  { key: "receiving_yards", type: "number" },
  { key: "receiving_tds", type: "number" },
  { key: "receiving_2pt_conversions", type: "number" },
  { key: "yards_per_carry", type: "number" },
  { key: "dom", type: "number" },
  { key: "receiving_first_downs", type: "number" },
  { key: "dakota", type: "number" },
  { key: "ppr_sh", type: "number" },
  { key: "rtd_sh", type: "number" },
  { key: "receiving_air_yards", type: "number" },
  { key: "air_yards_share", type: "number" },
  { key: "wopr_x", type: "number" },
  { key: "yac_sh", type: "string" },
  { key: "games", type: "number" },
  { key: "racr", type: "number" },
  { key: "w8dom", type: "number" },
  { key: "passing_epa", type: "number" },
  { key: "tgt_sh", type: "number" },
  { key: "ry_sh", type: "number" },
  { key: "rfd_sh", type: "number" },
  { key: "special_teams_tds", type: "number" },
  { key: "rtdfd_sh", type: "number" },
  { key: "targets", type: "number" },
  { key: "pacr", type: "number" },
  { key: "receiving_yards_after_catch", type: "number" },
  { key: "receiving_epa", type: "number" },
  { key: "scrimmage_yards", type: "number" },
  { key: "yptmpa", type: "number" },
  { key: "fantasy_points", type: "number" },
];

export const PLAYERSEASON_STATS_SEASON = [
  ...PLAYERSEASON_STATS,
  { key: "teams", type: "string" }, // many teams per player per season
];

export const PLAYERSEASON_STATS_GAME = [
  ...PLAYERSEASON_STATS,
  { key: "recent_team", type: "string" }, // one team per player per game
];
