export const PLAYERGAME_STATS = [
  { key: "position_group", type: "string" },
  { key: "season_type", type: "string" },
  { key: "completions", type: "number" },
  { key: "attempts", type: "number" },
  { key: "passing_yards", type: "number" },
  { key: "passing_tds", type: "number" },
  { key: "interceptions", type: "number" },
  { key: "sacks", type: "number" },
  { key: "sack_yards", type: "number" },
  { key: "sack_fumbles", type: "boolean" },
  { key: "sack_fumbles_lost", type: "boolean" },
  { key: "passing_air_yards", type: "number" },
  { key: "passing_yards_after_catch", type: "number" },
  { key: "passing_first_downs", type: "number" },
  { key: "passing_2pt_conversions", type: "boolean" },
  { key: "carries", type: "number" },
  { key: "rushing_yards", type: "number" },
  { key: "rushing_tds", type: "number" },
  { key: "rushing_fumbles", type: "number" },
  { key: "rushing_fumbles_lost", type: "number" },
  { key: "rushing_first_downs", type: "number" },
  { key: "rushing_epa", type: "number" },
  { key: "rushing_2pt_conversions", type: "boolean" },
  { key: "receptions", type: "number" },
  { key: "receiving_fumbles", type: "number" },
  { key: "fantasy_points_ppr", type: "number" },
  { key: "receiving_fumbles_lost", type: "number" },
  { key: "passing_interceptions", type: "number" },
  { key: "target_share", type: "number" },
  { key: "receiving_yards", type: "number" },
  { key: "receiving_tds", type: "number" },
  { key: "yards_per_carry", type: "number" },
  { key: "receiving_2pt_conversions", type: "boolean" },
  { key: "wopr", type: "number" },
  { key: "receiving_first_downs", type: "number" },
  { key: "headshot_url", type: "string" },
  { key: "dakota", type: "number" },
  { key: "receiving_air_yards", type: "number" },
  { key: "air_yards_share", type: "number" },
  { key: "def_interceptions", type: "number" },
  { key: "racr", type: "number" },
  { key: "def_interception_yards", type: "number" },
  { key: "passing_epa", type: "number" },
  { key: "def_sacks", type: "number" },
  { key: "def_sack_yards", type: "number" },
  { key: "special_teams_tds", type: "number" },
  { key: "targets", type: "number" },
  { key: "pacr", type: "number" },
  { key: "receiving_yards_after_catch", type: "number" },
  { key: "receiving_epa", type: "number" },
  { key: "scrimmage_yards", type: "number" },
  { key: "fantasy_points", type: "number" },
];

export const PLAYERGAME_STATS_SEASON = [
  ...PLAYERGAME_STATS,
  { key: "teams", type: "string" }, // many teams per player per season
];

export const PLAYERGAME_STATS_GAME = [
  ...PLAYERGAME_STATS,
  { key: "recent_team", type: "string" }, // one team per player per game
];
