name: Data Ingestion

on:
  workflow_dispatch: # Allows manual trigger
  # Each trigger is 30 minutes after each NFLVerse pbp trigger
  # See: https://github.com/nflverse/nflverse-pbp/blob/866020fdf54bee79ea11b6cf69168d438dd26dea/.github/workflows/update_data.yaml#L3-L13
  schedule:
    # Every day at 9:30 UTC/5:00 ET
    - cron: "30 9 * 1,2,9-12 *"
    # TNF 5:30 AM UTC / 12:30 AM ET
    - cron: "00 6 * 1,2,9-12 5"
    # Early window: 10:30 PM UTC / 5:00 PM ET
    - cron: "30 22 * 1,2,9-12 0"
    # Late window: 0:35 UTC / 8:00 ET
    - cron: "35 0 * 1,2,9-12 1"
    # SNF/MNF: 5:30 UTC / 12:30 ET
    - cron: "00 6 * 1,2,9-12 1"
    - cron: "00 6 * 1,2,9-12 2"

env:
  NEO4J_STATFOUNDRY_NFL_AURA_URI_CLONE: ${{ secrets.NEO4J_STATFOUNDRY_NFL_AURA_URI_CLONE }}
  NEO4J_STATFOUNDRY_NFL_AURA_USERNAME: ${{ secrets.NEO4J_STATFOUNDRY_NFL_AURA_USERNAME }}
  NEO4J_STATFOUNDRY_NFL_AURA_PASSWORD_CLONE: ${{ secrets.NEO4J_STATFOUNDRY_NFL_AURA_PASSWORD_CLONE }}

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: service

      - name: Run weekly games ingestion
        id: load_games
        run: python -m scripts.etl.cypher.load_games
        working-directory: service

      - name: Run weekly team stats ingestion
        if: steps.load_games.outcome == 'success'
        run: python -m scripts.etl.cypher.load_teamgames
        working-directory: service

      - name: Run team season stats ingestion
        if: steps.load_games.outcome == 'success'
        run: python -m scripts.etl.cypher.load_teamseasons
        working-directory: service

      - name: Run weekly player stats ingestion
        if: steps.load_games.outcome == 'success'
        run: python -m scripts.etl.cypher.load_playergames
        working-directory: service

      - name: Run weekly plays ingestion
        if: steps.load_games.outcome == 'success'
        run: python -m scripts.etl.cypher.load_plays
        working-directory: service
